name: smart_society_new
description: A new Flutter application.


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  pin_code_fields: ^6.0.1
  syncfusion_flutter_datepicker: any
#  firebase_core: ^0.5.0
#  firebase_core: any
#  image_picker: ^0.6.3+1
  fluttertoast: ^3.1.0
  flutter_sms: any
  twilio_flutter: any
  speech_recognition: ^0.3.0+1
  speech_to_text: ^3.1.0
  carousel_slider: ^1.4.1
  flutter_otp: ^0.3.2
  flutter_downloader: any
  chips_choice: ^2.0.1
  date_format: any
  multi_select_flutter: any
  flutter_swiper: ^1.1.6
  dio: ^3.0.3
  progress_dialog: ^1.2.0
  month_picker_dialog: any
  shared_preferences: ^0.5.3+4
  xml2json: ^4.0.0
#  google_map_location_picker: any
  #  share: ^0.6.4+3
  flutter_native_image: ^0.0.4
  url_launcher: ^5.2.5
  flutter_google_places: ^0.2.4
  esys_flutter_share: ^1.0.2
  dotted_border: ^1.0.7

  flutter_staggered_animations: ^0.1.3
  bottom_navy_bar: ^5.2.0
  contacts_service: ^0.4.6
  package_info: ^0.4.0+16
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_webview_plugin: ^0.3.10
  permission_handler: any
  firebase_remote_config: any
  pin_input_text_field: ^3.0.2
  http: ^0.12.0+2
  screenshot: ^0.3.0
  multiselect_formfield: ^0.1.2
  qr_flutter: ^3.1.0
  cloud_firestore: any
  datetime_picker_formfield: ^1.0.0
#  firebase_messaging: ^6.0.9
  draggable_fab: ^0.1.1
  onesignal_flutter: ^2.6.3
  flutter_local_notifications: any
  google_maps_flutter: ^1.2.0
  location: ^2.3.5
  google_maps_webservice: ^0.0.19
  geolocator: ^6.1.6
  imei_plugin: ^1.2.0
  youtube_player_flutter: ^7.0.0+7
  get: ^3.24.0
  flutter_staggered_grid_view: ^0.3.0
  sqflite: ^1.1.6+4
  barcode_scan: ^1.0.0
  fl_chart: ^0.4.1
  searchable_dropdown: ^1.1.3

  easy_permission_validator: ^1.0.5
  flutter_multiple_image_picker: ^0.0.1
  file_picker: ^1.4.2
  double_back_to_close_app: ^1.2.0
  flutter_svg: ^0.17.3+1
  flutter_share_me: ^0.9.1
  flutter_share: ^1.0.2+1
  flutter_rating_bar: ^3.0.1+1
  flutter_custom_clippers: ^1.1.1
  agora_rtm: any
  image_picker: ^0.6.7+2
  intro_slider: ^2.3.3
  multi_image_picker: ^4.7.14
  share: ^0.6.5+4
  geocoder: ^0.2.1
  flutter_slidable: ^0.5.4
  simple_animations: any
#  permission_handler: ^5.0.1+1
  path_provider: ^1.2.0
  intl: ^0.16.1
  pull_to_refresh: any
  unique_identifier: any
  provider: ^2.0.0
  clipboard: ^0.1.2+8
  convex_bottom_bar: any
  flutter_statusbarcolor: ^0.2.3
  razorpay_flutter: ^1.2.2
  webview_flutter: ^0.3.14+1
  firebase_auth: any
  carousel_pro: ^1.0.0
  flutter_spinkit: ^4.1.2+1
  dotted_decoration: ^1.2.2
  overlay_support: ^1.0.3
  pie_chart: ^3.1.1
  charts_flutter: ^0.10.0
  flutter_dtmf: ^0.0.3
  flutter_masked_text: ^0.8.0
  vibration: ^1.7.3
  agora_rtc_engine: ^1.0.13
  easy_gradient_text: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/Building.png
    - images/Back.png
    - images/verify.png
    - images/Back.png
    - images/Building.png
    - images/complaint.png
    - images/directory.png
    - images/document.png
    - images/emergency.png
    - images/gallery.png
    - images/Helpdesk.png
    - images/information.png
    - images/polling.png
    - images/Rules.png
    - images/Utilities.png
    - images/Vendors.png
    - images/Maintainence.png
    - images/Complain.png
    - images/Camera.png
    - images/smartphone.png
    - images/applogo.png
    - images/phone.png
    - images/Blood.png
    - images/gender.png
    - images/automobile.png
    - images/ElectronicIcon.png
    - images/plumbing.png
    - images/pest_control.png
    - images/toolbox.png
    - images/acserviceicon.png
    - images/success.png
    - images/error.png
    - images/whatsapp.png
    - images/wing.png
    - images/no_data.png
    - images/Logout.png
    - images/waiting.png
    - images/man.png
    - images/guest.png
    - images/placeholder.png
    - images/AMC.png
    - images/label.png
    - images/NoRules.png
    - images/file.png
    - images/Cake.png
    - images/family.png
    - images/public.png
    - images/alert.png
    - images/call.png
    - images/moeny.png
    - images/megaphone.png
    - images/image_loading.gif
    - images/advertisement.jpg
    - images/record.gif
    - images/profile_update.png
    - images/swimmer.png
    - images/background.png
    - images/gini.png
    - images/myginitext.png
    - images/deny.png
    - images/callvisitor.png
    - images/mail.png
    - images/navigation.png
    - images/DailyHelp.png
    - images/user.png
    - images/emergancycall.png
    - images/facebook.png
    - images/instagram.png
    - images/website.png
    - images/galleryselect.png
    - images/bill.png
    - images/leaveatgate.png
    - lib/Member_App/Mall/Images/daawat.png
    - images/Logo.png
    - images/notification_icon.png
    - images/delete_icon.png
    - images/edit_icon.png
    - images/no_image.png
    - images/directory_dashboard.png
    - images/document_dashboard.png
    - images/notice_dashboard.png
    - images/document_icon.png
    - images/icon_scanner.png
    - images/visitor_icon.png
    - images/whatsapp_icon.png
    - images/rules_icon.png
    - images/rules_small_icon.png
    - images/attach_download.png
    - images/complaint_icon.png
    - images/complaint_icon_small.png
    - images/Blood.png
    - images/gender.png
    - images/emergency.png
    - images/event.png
    - images/income.png
    - images/expense.png
    - images/no_image2.png
    - images/image_loading.gif
    - images/balance_sheet.png
    - images/Profile_icon.png
    - images/give-money.png
    - images/Building.png
    - images/money_icon.png
    - images/reference_icon.png
    - images/maintenance_icon.png
    - images/admin_polling.png
    - images/question.png
    - images/maintenance_create.png
    - images/scanner.png
    - images/deliveryboy.png
    - images/user.png
    - images/noimg.png
    - images/amc_icon.png
    - images/gini.png
    - images/myginitext.png
    - images/background.png
    - images/Staff.png
    - images/leaveatgate.png
    - images/error.png
    - images/mySociety.png
    - images/info.png
    - images/societyRules.png
    - images/bank.png
    - images/statistics.png
    - images/event_society.png
    - images/gallary_admin.png
    - images/phone1.png
    - images/Ad1.jpg
    - images/youtube.png
    - images/whatsapplogo1.png
    - images/gmail.png
    - images/telephone.png
    - images/sale.png
    - images/close.png
    - images/wishlist.png
    - images/StarRating.jpg
    - images/amcimage.jpg
    - images/society1.jpg
    - images/thankyou.png
    - images/correctsign.png
    - images/video_call.png
    - images/
    - images/reminder.png
    - images/medicine.png
#    - images/pencil.png
    - images/drop.png
    - images/WatchmanCall.png
    - images/bloodplasma.png
    - images/bloodplasmareceiver.png
    - images/bloodplasmadonor.png
    - images/pendingapproval.png
    - images/amenities.png
    - images/familymember.png
    - images/dailyresource.png
    - images/assistance.png
    - images/homescreenprofile.png
    - images/visitors.png
    - images/deals.png
    - images/home.png
    - images/gatepass.png
    - images/SOS.png
    - images/sweeper.png
    - images/maid.png
    #    - assets/assets/
#    - images/bike.png
    - assets/
    - assets/ringing.mp3
    - assets/ringer.mp3
    - assets/ambulance.mp3
#    - assets/8247_htc_h10.mp3



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages






  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
